name: Delete noisy AWS Amplify comments
on:
  issue_comment:
    types: [created]
jobs:
  poof:
    if: startsWith(github.event.comment.user.login, 'aws-amplify') && contains(github.event.comment.body, 'This pull request is automatically being deployed by Amplify Hosting')
    runs-on: ubuntu-latest
    steps:
      - run: gh api -X DELETE '${{ github.event.comment.url }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
