name: Security Audit
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read Node.js version
        uses: nodenv/actions-node-version@v2.0.10
        id: nodenv
      - name: Set Node.js ${{ steps.nodenv.outputs.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ steps.nodenv.outputs.node-version }}
      - name: Install npm and yarn
        run: npm i npm yarn@1 -g
      - name: Audit
        run: yarn audit
