name: Contiinuous Integration
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x
      - name: Install npm and yarn
        run: npm i npm yarn@1 -g
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
